### ISSUE TITLE
Where should I begin in order to use this?

### ISSUE THREAD

**Issue by smlee-hdactech** [injae/cppm#34]
I have built and installed cppm on windows. However, though I had run "cppm init", nothing was executed.
In case of, "cppm cppkg search json", the program was crashed.
Where should I begin in order to use this?

**Comment by injae** [comment]
You must register the cppm binary with Windows PATH.
The default PATH is installed on C:\Program Files (x86)\cppm\bin .

**Comment by smlee-hdactech** [comment]
PATH has already included the binary path for cppm. The captured image is like the following.

![image](https://user-images.githubusercontent.com/43371933/51735483-e5a83700-20ca-11e9-8f0c-cba77036c843.png)

**Comment by injae** [comment]
혹시 한국인 아니신가요 한국인이시면 한국어로 해도 될까요?

2019년 1월 25일 (금) 오후 6:02에 smlee-hdactech <notifications@github.com>님이 작성:

**Comment by smlee-hdactech** [comment]
한국분이시군요. 훨씬 편하게 대화할 수 있겠네요. 문제 상황은 캡쳐한대로 입니다. 해결 방안이 있을까요?

**Comment by injae** [comment]
혹시 컴파일하실때 에러가 없었나요?

**Comment by injae** [comment]
Cppm init은 -b or -l옵션이랑 이름이 필요합니다 
예) cppm init -b exam

**Comment by smlee-hdactech** [comment]
컴파일 시에 특별한 오류는 못 봤습니다.
cppm init -b exam 로 실행은 잘 되는 것 같습니다. 기본 디렉토리가 만들어지네요.
그 다음에 해야 할 일은 무엇인가요? cppm.toml 파일은 기본 생성해주진 않는 건지요?

**Comment by injae** [comment]
기본 cppm.toml파일도 생성이될겁니다. 혹시 생성이 안됬다면 생성된 디렉토리를 보여주실수있나요?

**Comment by smlee-hdactech** [comment]
cppm init -b exam 를 실행해서 exam 이라는 디렉토리가 생성되었고, 내부는 다음과 같습니다.
![image](https://user-images.githubusercontent.com/43371933/51889424-ec8dbd00-23dc-11e9-9295-b0a4ea217d22.png)

**Comment by injae** [comment]
혹시 최신버전 다운 받으신건가요?

**Comment by injae** [comment]
정상적으로 작동하면 이렇게 생성됩니다.
![default](https://user-images.githubusercontent.com/16817498/51892635-e6e8a500-23e5-11e9-8271-9f2201b16725.PNG)

**Comment by smlee-hdactech** [comment]
예.. 최신 버전이고, 다시 새롭게 다운로드 받아 빌드하고 실행해봐도 동일하군요.
혹시 윈도우에서 작업은 WSL을 이용하신건가요?

**Comment by injae** [comment]
wsl은 사용하지않고, 비주얼 스튜디오 2017과 cmake만 설치한 상태에서 실행했습니다.
